# Generated by Django 3.2.25 on 2025-04-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
